Work around Amazon Linux 2 repository issue
simp/rubygem-simp-beaker-helpers pull request #176
Opened 2022-03-20 23:35 UTC by trevor-vaughan

Closes #175

2022-03-28 17:45 UTC, op-ct commented on .gitlab-ci.yml
> +      if (( os == 'Amazon' ) && ( "#{release}" == '2' ))
This and breaks the `.gitlab-ci.yml` and looks like it's probably misplaced Ruby copypasta meant for something else.

```suggestion
```

2022-03-29 18:09 UTC, op-ct requested changes
This still fails on Amazon Linux 2: https://gitlab.com/simp/rubygem-simp-beaker-helpers/-/jobs/2260389857 ― the URLs in the `.repo` files delivered by simp-release-community use `$releasever`, which still resolves to `2` despite the workaround in `install_simp_repos`.  

I'm taking a look adding a fix to the upstream repo for simp-release-community.

2022-03-31 17:31 UTC, op-ct commented
Submitted an upstream MR to the simp-release-* RPMs

2022-04-17 19:19 UTC, trevor-vaughan commented
@op-ct I had some bad logic in the workaround code. Just rebased and submitted a fix that appears to work.

2022-05-06 21:44 UTC, op-ct approved these changes
The hack-around is sketch, but it gets us far enough to get to the next steps.

2022-05-06 21:45 UTC, merged